data = [
    {
        "_id": "1",
        "title": "Boogie Board",
        "description":"This is a boogie board",
        "image": "boogie-board.jpg",
        "price": 59.99,
        "stock": 20,
        "category": "Other Boards",
        "discount": 5,
    },
    {
        "_id": "2",
        "title": "Grom Board",
        "description":"This is a board for kids",
        "image": "gromboard.jpg",
        "price": 175.99,
        "stock": 20,
        "category": "Surf Boards",
        "discount": 5,
    },
    {
        "_id": "3",
        "title": "Hybrid Board",
        "description":"This is a hybrid step up board",
        "image": "hybrid-board.jpg",
        "price": 599.99,
        "stock": 20,
        "category": "Surf Boards",
        "discount": 5,
    },
    {
        "_id":"4",
        "title": "Longboard",
        "description":"This is a long board",
        "image": "longboard.jpg",
        "price": 899.99,
        "stock": 20,
        "category": "Surf Boards",
        "discount": 5,
    },
    {
        "_id":"5",
        "title": "Midlength Board",
        "description":"This is a mid length board",
        "image": "Midlength-board.jpg",
        "price": 399.99,
        "stock": 20,
        "category": "Surf Boards",
        "discount": 5,
    },
    {
        "_id":"6",
        "title": "Short Board",
        "description":"This is a short board",
        "image": "shortboard.jpg",
        "price": 699.99,
        "stock": 20,
        "category": "Surf Boards",
        "discount": 5,
    },
    {
        "_id":"7",
        "title": "Softboard",
        "description":"This is a soft top board",
        "image": "softboard.jpg",
        "price": 199.99,
        "stock": 20,
        "category": "Other Boards",
        "discount": 5,
    },
    {
        "_id":"8",
        "title": "Skim Board",
        "description":"This is a skim board",
        "image": "skimboard.jpg",
        "price": 79.99,
        "stock": 20,
        "category": "Other Boards",
        "discount": 5,
    },
    {
        "_id":"9",
        "title": "Step Up Board",
        "description":"This is a step board",
        "image": "stepupboard.jpg",
        "price": 399.99,
        "stock": 20,
        "category": "Surf Boards",
        "discount": 5,
    }, 
]